Change the ebsnvme-id script from Python to Bash (using nvme-cli)

diff --git a/ebsnvme-id b/ebsnvme-id
--- a/ebsnvme-id
+++ b/ebsnvme-id
@@ -1,4 +1,4 @@
-#!/usr/bin/env python3
+#!/usr/bin/bash
 
 # Copyright Amazon.com, Inc. and its affiliates. All Rights Reserved.
 #
@@ -6,169 +6,162 @@
 # for the specific language governing permissions and limitations under
 # the License.
 
-"""
-Usage:
-Read EBS device information and provide information about
-the volume.
-"""
+# Bash/Unix implementation of ebsnvme-id that requires nvme-cli >= 1.13
+# Since this has to run inside initramfs, this is not using getopt/getopts.
 
-from __future__ import print_function
-import argparse
-from ctypes import Structure, c_uint8, c_uint16, \
-        c_uint32, c_uint64, c_char, addressof, sizeof
-from fcntl import ioctl
-import sys
+# Change this in case your distro puts nvme-cli in a different location
+NVME=/usr/sbin/nvme
 
-NVME_ADMIN_IDENTIFY = 0x06
-NVME_IOCTL_ADMIN_CMD = 0xC0484E41
-AMZN_NVME_VID = 0x1D0F
-AMZN_NVME_EBS_MN = "Amazon Elastic Block Store"
+# The EBS model name
+EBS_MN="Amazon Elastic Block Store"
 
+##
+# Ensures that the kernel device name in $1 is actually an EBS volume.
+ensure_ebs_volume() {
+  local device=$1
+  local mn
 
-class nvme_admin_command(Structure):
-    _pack_ = 1
-    _fields_ = [("opcode", c_uint8),      # op code
-                ("flags", c_uint8),       # fused operation
-                ("cid", c_uint16),        # command id
-                ("nsid", c_uint32),       # namespace id
-                ("reserved0", c_uint64),
-                ("mptr", c_uint64),       # metadata pointer
-                ("addr", c_uint64),       # data pointer
-                ("mlen", c_uint32),       # metadata length
-                ("alen", c_uint32),       # data length
-                ("cdw10", c_uint32),
-                ("cdw11", c_uint32),
-                ("cdw12", c_uint32),
-                ("cdw13", c_uint32),
-                ("cdw14", c_uint32),
-                ("cdw15", c_uint32),
-                ("reserved1", c_uint64)]
+  if [[ ! -b /dev/$device ]]; then
+    echo "[ERROR] /dev/$device is not a block device" >&2
+    exit 1
+  fi
 
+  mn="$(read_nvme_attr "$device" mn || printf "<unknown>")"
 
-class nvme_identify_controller_amzn_vs(Structure):
-    _pack_ = 1
-    _fields_ = [("bdev", c_char * 32),  # block device name
-                ("reserved0", c_char * (1024 - 32))]
+  if [[ $mn != "${EBS_MN}" ]]; then
+    echo "[ERROR] /dev/$device is not an EBS device, but is $mn" >&2
+    exit 1
+  fi
+}
 
+##
+# Prints the block device mapping name for the device specified in $1
+print_block_device_mapping() {
+  local device=$1
+  local bdev
 
-class nvme_identify_controller_psd(Structure):
-    _pack_ = 1
-    _fields_ = [("mp", c_uint16),       # maximum power
-                ("reserved0", c_uint16),
-                ("enlat", c_uint32),     # entry latency
-                ("exlat", c_uint32),     # exit latency
-                ("rrt", c_uint8),       # relative read throughput
-                ("rrl", c_uint8),       # relative read latency
-                ("rwt", c_uint8),       # relative write throughput
-                ("rwl", c_uint8),       # relative write latency
-                ("reserved1", c_char * 16)]
+  ensure_ebs_volume "$device"
 
+  bdev=$(read_nvme_attr "$device" bdev)
 
-class nvme_identify_controller(Structure):
-    _pack_ = 1
-    _fields_ = [("vid", c_uint16),          # PCI Vendor ID
-                ("ssvid", c_uint16),        # PCI Subsystem Vendor ID
-                ("sn", c_char * 20),        # Serial Number
-                ("mn", c_char * 40),        # Module Number
-                ("fr", c_char * 8),         # Firmware Revision
-                ("rab", c_uint8),           # Recommend Arbitration Burst
-                ("ieee", c_uint8 * 3),      # IEEE OUI Identifier
-                ("mic", c_uint8),           # Multi-Interface Capabilities
-                ("mdts", c_uint8),          # Maximum Data Transfer Size
-                ("reserved0", c_uint8 * (256 - 78)),
-                ("oacs", c_uint16),         # Optional Admin Command Support
-                ("acl", c_uint8),           # Abort Command Limit
-                ("aerl", c_uint8),          # Asynchronous Event Request Limit
-                ("frmw", c_uint8),          # Firmware Updates
-                ("lpa", c_uint8),           # Log Page Attributes
-                ("elpe", c_uint8),          # Error Log Page Entries
-                ("npss", c_uint8),          # Number of Power States Support
-                ("avscc", c_uint8),         # Admin Vendor Specific Command Configuration # noqa
-                ("reserved1", c_uint8 * (512 - 265)),
-                ("sqes", c_uint8),          # Submission Queue Entry Size
-                ("cqes", c_uint8),          # Completion Queue Entry Size
-                ("reserved2", c_uint16),
-                ("nn", c_uint32),            # Number of Namespaces
-                ("oncs", c_uint16),         # Optional NVM Command Support
-                ("fuses", c_uint16),        # Fused Operation Support
-                ("fna", c_uint8),           # Format NVM Attributes
-                ("vwc", c_uint8),           # Volatile Write Cache
-                ("awun", c_uint16),         # Atomic Write Unit Normal
-                ("awupf", c_uint16),        # Atomic Write Unit Power Fail
-                ("nvscc", c_uint8),         # NVM Vendor Specific Command Configuration # noqa
-                ("reserved3", c_uint8 * (704 - 531)),
-                ("reserved4", c_uint8 * (2048 - 704)),
-                ("psd", nvme_identify_controller_psd * 32),  # Power State Descriptor # noqa
-                ("vs", nvme_identify_controller_amzn_vs)]  # Vendor Specific
+  if [[ -z $bdev ]]; then
+    echo "[ERROR] /dev/$device has no block device mapping available" >&2
+    exit 1
+  fi
 
+  echo "${bdev}"
+}
 
-class ebs_nvme_device:
-    def __init__(self, device):
-        self.device = device
-        self.ctrl_identify()
+##
+# Prints udev env vars for the device specified in $1
+print_udev_env() {
+  local device=$1
+  local bdev
+  local volid
 
-    def _nvme_ioctl(self, id_response, id_len):
-        admin_cmd = nvme_admin_command(opcode=NVME_ADMIN_IDENTIFY,
-                                       addr=id_response,
-                                       alen=id_len,
-                                       cdw10=1)
+  ensure_ebs_volume "$device"
 
-        with open(self.device, "r") as nvme:
-            ioctl(nvme, NVME_IOCTL_ADMIN_CMD, admin_cmd)
+  bdev=$(read_nvme_attr "$device" bdev)
+  volid=$(read_volume_id "$device")
 
-    def ctrl_identify(self):
-        self.id_ctrl = nvme_identify_controller()
-        self._nvme_ioctl(addressof(self.id_ctrl), sizeof(self.id_ctrl))
+  if [[ -z $bdev || -z $volid ]]; then
+    echo "[ERROR] /dev/$device cannot determine udev environment" >&2
+    exit 1
+  fi
 
-        if self.id_ctrl.vid != AMZN_NVME_VID \
-                or self.id_ctrl.mn.decode().strip() != AMZN_NVME_EBS_MN:
-            raise TypeError("[ERROR] Not an EBS device: '{0}'".format(self.device)) # noqa
+  echo "_EC2_BLOCK_DEVICE_MAPPING=${bdev}"
+  echo "_EBS_VOLUME_ID=${volid}"
+}
 
-    def get_volume_id(self):
-        vol = self.id_ctrl.sn.decode()
+##
+# Prints the volume ID for the device specified in $1
+print_volume_id() {
+  local device=$1
+  local vol_id
 
-        if vol.startswith("vol") and vol[3] != "-":
-            vol = "vol-" + vol[3:]
+  vol_id=$(read_volume_id "$device")
 
-        return vol
+  echo "Volume ID: ${vol_id}"
+}
 
-    def get_block_device(self, stripped=False):
-        dev = self.id_ctrl.vs.bdev.decode().strip()
+##
+# Reads the NVMe attribute specified by $2 from the device specified in $1
+read_nvme_attr() {
+  local device=$1
+  local nvme_attr=$2
 
-        if stripped and dev.startswith("/dev/"):
-            dev = dev[5:]
+  ${NVME} amzn id-ctrl "/dev/${device}" | while read -r line; do
+    if [[ $line =~ ^${nvme_attr}[[:space:]]*: ]]; then
+      printf "%s" "${line#*: }"
+      return 0
+    fi
+  done
 
-        return dev
+  return 1
+}
 
+##
+# Reads the volume ID for the device specified in $1 and parses it into a
+# regular EBS vol-abcdef12345 format.
+read_volume_id() {
+  local device=$1
+  local sn
 
-if __name__ == "__main__":
-    parser = \
-        argparse.ArgumentParser(description="Reads EBS information from NVMe devices.") # noqa
-    parser.add_argument("device", nargs=1, help="Device to query")
+  ensure_ebs_volume "$device"
 
-    display = parser.add_argument_group("Display Options")
-    display.add_argument("-v", "--volume", action="store_true",
-                         help="Return volume-id")
-    display.add_argument("-b", "--block-dev", action="store_true",
-                         help="Return block device mapping")
-    display.add_argument("-u", "--udev", action="store_true",
-                         help="Output data in format suitable for udev rules")
+  sn=$(read_nvme_attr "$device" sn)
 
-    if len(sys.argv) < 2:
-        parser.print_help()
-        sys.exit(1)
+  if [[ -z $sn ]]; then
+    echo "[ERROR] /dev/$device has no volume ID available" >&2
+    exit 1
+  fi
 
-    args = parser.parse_args()
+  # Strip the prefix, which is usually vol, but we should tolerate vol- too
+  local without_prefix=${sn#vol}
 
-    get_all = not (args.udev or args.volume or args.block_dev)
+  # Print out vol-XXX after stripping the - prefix which is probably not present
+  printf "vol-%s" "${without_prefix#-}"
+}
 
-    try:
-        dev = ebs_nvme_device(args.device[0])
-    except (IOError, TypeError) as err:
-        print(err, file=sys.stderr)
-        sys.exit(1)
+##
+# Prints program usage information and exits
+usage() {
+  echo "usage: ebsnvme-id [OPTION]
 
-    if get_all or args.volume:
-        print("Volume ID: {0}".format(dev.get_volume_id()))
-    if get_all or args.block_dev or args.udev:
-        print(dev.get_block_device(args.udev))
+Reads EBS information from NVMe devices.
+
+Options:
+  -h            show this help message and exit
+  -v DEVICE     Return volume ID
+  -b DEVICE     Return block device mapping
+  -u DEVICE     Deprecated alias for -b DEVICE
+  -U DEVICE     Output data in a format suitable to be used as an IMPORT{program} in a udev rule
+"
+}
+
+# Check if we have enough arguments
+if [[ $# -ne 2 ]]; then
+  usage
+  exit 1
+fi
+
+# Name the arguments and strip any leading /dev
+option="$1"
+device="${2#/dev/}"
+
+# Parse options
+case $option in
+  -U)
+    print_udev_env "$device"
+    ;;
+  -b | -u)
+    print_block_device_mapping "$device"
+    ;;
+  -v)
+    print_volume_id "$device"
+    ;;
+  *)
+    usage
+    exit 1
+    ;;
+esac
